
form:
    path:     /form
    defaults: { _controller: UtilisateurBundle:Utilisateur:testformulaire }
    
factures:
    path:     /profile/factures
    defaults: { _controller: UtilisateurBundle:Utilisateur:factures }
    
facturesPDF:
    path:     /profile/factures/pdf/{id}
    defaults: { _controller: UtilisateurBundle:Utilisateur:generateFacturePDF }

routingAdminUtilisateurs:
    resource: "@UtilisateurBundle/Resources/config/routing/utilisateurs.yml"
    prefix: /admin/utilisateurs/