utilisateur:
    resource: "@UtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

journal:
    resource: "@journalBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"