# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    getFacture  : 
        class : journalBundle\Services\GetFacture
        arguments : [@service_container]
    setNewReference  : 
        class : journalBundle\Services\GetReference
        arguments : [@security.context , @doctrine.orm.entity_manager]
    tva:
        class: journalBundle\Twig\Extension\TvaExtension
        tags:
            - { name: twig.extension }

    MontantTVA:
        class: journalBundle\Twig\Extension\MontantTVAExtension
        tags:
            - { name: twig.extension }
  
    RedirectionListener :     
        class : journalBundle\Listener\RedirectionListener
        arguments : [@service_container , @session]
        tags : 
            - {name: kernel.event_listener , event : kernel.request  , method : onKernelRequest}