panier:
    path:     /panier
    defaults: { _controller: journalBundle:Panier:panier }

livraison:
    path:     /livraison
    defaults: { _controller: journalBundle:Panier:livraison }
validation:
    path:     /validation
    defaults: { _controller: journalBundle:Panier:validation }
ajouter :
    path:     /ajouter/{id}
    defaults: { _controller: journalBundle:Panier:ajouter }
supprimer :
    path:     /supprimer/{id}
    defaults: { _controller: journalBundle:Panier:supprimer }
    
livraisaonSuppressionAdresse :
    path:     /livraisaonSuppressionAdresse/{id}
    defaults: { _controller: journalBundle:Panier:livraisaonSuppressionAdresse }
    