<?php

namespace journalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends EntityRepository
{
    public function byFacture($utilisateur) {
        $qb = $this->createQueryBuilder('u')
                ->select()
                ->where('u.utilisateur =:utilisateur')
                ->andWhere('u.reference != 0')
                ->andWhere('u.valider != 0')
                ->orderBy('u.id')
                ->setParameter('utilisateur', $utilisateur);
            
        return $qb->getQuery()->getResult(); 
    }
}
