<?php

namespace journalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{
    
    public function  findByCategorie($categorie){
        $querybuilder = $this->createQueryBuilder('p')
                ->select('p')
                ->where('p.categorie = :categorie')
                ->orderBy('p.id')
                ->setParameter('categorie', $categorie);
                return $querybuilder->getQuery()->getResult(); 
        
    } 
}
