<?php

namespace journalBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{
    public function findArray($Array){
        $qb = $this->createQueryBuilder('p')
                ->select('p')
                ->where('p.id IN (:array)')
                ->setParameter('array', $Array);
        return $qb->getQuery()->getResult();
    }
    public function  findByCategorie($categorie){
        $querybuilder = $this->createQueryBuilder('p')
                ->select('p')
                ->where('p.categorie = :categorie')
                ->andWhere('p.disponible = 1')
                ->orderBy('p.id')
                ->setParameter('categorie', $categorie);
                return $querybuilder->getQuery()->getResult(); 
        
    } 
    public function recherche($chaine){
        $qb = $this->createQueryBuilder('p')
                ->select('p')
                ->where('p.nom like  :chaine')
                   ->andWhere('p.disponible = 1')
                ->orderBy('p.id')
                ->setParameter('chaine','%'.$chaine.'%');
        
         return $qb->getQuery()->getResult(); 
    }
}
