routingPanier:
    resource: "@journalBundle/Resources/config/routing/routingPanier.yml"
    prefix: /

    
routingProduits:
    resource: "@journalBundle/Resources/config/routing/routingProduits.yml"
    prefix: /
 
routingCommande:
    resource: "@journalBundle/Resources/config/routing/routingCommandes.yml"
    prefix: /

routingAdminProduits:
    resource: "@journalBundle/Resources/config/AdminRouting/produits.yml"
    prefix: /admin/produits/
    
routingAdminCategories:
    resource: "@journalBundle/Resources/config/AdminRouting/categories.yml"
    prefix: /admin/categorie/

routingAdminCommandes:
    resource: "@journalBundle/Resources/config/AdminRouting/commandes.yml"
    prefix: /admin/commandes/