routingPanier:
    resource: "@journalBundle/Resources/config/rooting/routingPanier.yml"
    prefix: /

    
routingProduits:
    resource: "@journalBundle/Resources/config/rooting/routingProduits.yml"
    prefix: /
 
routingCommande:
    resource: "@journalBundle/Resources/config/rooting/routingCommandes.yml"
    prefix: /