<?php

namespace UtilisateurBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillesRepository extends EntityRepository {

    public function  getCp($cp){
     $qb = $this->createQueryBuilder('p')
                ->select('p')
                ->where('p.villeCodePostal like  :cp')
                ->setParameter('cp','%'.$cp.'%')
                ->setMaxResults(1);
//        var_dump($qb->getQuery()); 
         $result =  $qb->getQuery()->getResult(); 
         if(count($result)>0)
         return $result[0]; 
         else return null ; 
    }
}
