AdminCategorie_index:
    path:     /
    defaults: { _controller: "journalBundle:CategoriesAdmin:index" }
    methods:  GET

AdminCategorie_show:
    path:     /{id}/show
    defaults: { _controller: "journalBundle:CategoriesAdmin:show" }
    methods:  GET

AdminCategorie_new:
    path:     /new
    defaults: { _controller: "journalBundle:CategoriesAdmin:new" }
    methods:  [GET, POST]

AdminCategorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "journalBundle:CategoriesAdmin:edit" }
    methods:  [GET, POST]

AdminCategorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "journalBundle:CategoriesAdmin:delete" }
    methods:  DELETE
