Utilisateursadresses:
    type: entity
    table: utilisateursadresses
    indexes:
        IDX_6CD1CF2CFB88E14F:
            columns:
                - utilisateur_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
        prenom:
            type: string
            nullable: false
            length: 255
            fixed: false
        telephone:
            type: string
            nullable: false
            length: 40
            fixed: false
        adresse:
            type: string
            nullable: false
            length: 255
            fixed: false
        cp:
            type: string
            nullable: false
            length: 10
            fixed: false
        pays:
            type: string
            nullable: false
            length: 125
            fixed: false
        ville:
            type: string
            nullable: false
            length: 125
            fixed: false
        complement:
            type: string
            nullable: true
            length: 255
            fixed: false
    manyToOne:
        utilisateur:
            targetEntity: Utilisateur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                utilisateur_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
